// Copyright (c) 2025 Una Partida Mas. All rights reserved.
// Licensed under the Valkarn Tasks License. See LICENSE.md in the repository root.

using System.Text;
using Microsoft.CodeAnalysis;

namespace UnaPartidaMas.Valkarn.Tasks.SourceGen.Generators
{
    /// <summary>
    /// Detects if UnityEngine.Awaitable is referenced in the compilation and generates
    /// extension methods for converting Awaitable/Awaitable{T} to ValkarnTask/ValkarnTask{T}.
    ///
    /// Direct 'await Awaitable' inside async ValkarnTask methods already works natively
    /// (Unity's Awaitable.Awaiter implements ICriticalNotifyCompletion, which the
    /// AsyncValkarnMethodBuilder accepts via its generic AwaitUnsafeOnCompleted).
    ///
    /// These generated .AsValkarnTask() methods enable explicit conversion for use with
    /// combinators (WhenAll, WhenAny) and task storage/passing patterns.
    ///
    /// Design: architecture.md §11.2, features.md §2
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class AwaitableBridgeGenerator : IIncrementalGenerator
    {
        const string AwaitableFullName = "UnityEngine.Awaitable";
        const string AwaitableGenericFullName = "UnityEngine.Awaitable`1";

        const string ValkarnTaskFullName = "UnaPartidaMas.Valkarn.Tasks.ValkarnTask";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Check if Awaitable AND ValkarnTask types exist in the compilation.
            // Without the ValkarnTask check, code is generated in assemblies that
            // don't reference Valkarn.Tasks, causing CS0246 errors.
            var awaitableInfo = context.CompilationProvider.Select(static (compilation, ct) =>
            {
                var valkarnTask = compilation.GetTypeByMetadataName(ValkarnTaskFullName);
                if (valkarnTask == null) return default;
                var awaitable = compilation.GetTypeByMetadataName(AwaitableFullName);
                var awaitableT = compilation.GetTypeByMetadataName(AwaitableGenericFullName);
                return new AwaitableAvailability(awaitable != null, awaitableT != null);
            });

            context.RegisterSourceOutput(awaitableInfo, static (ctx, info) => Generate(ctx, info));
        }

        static void Generate(SourceProductionContext ctx, AwaitableAvailability info)
        {
            if (!info.HasAwaitable && !info.HasAwaitableT)
                return;

            var sb = new StringBuilder(1024);
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#if UNITY_2023_1_OR_NEWER");
            sb.AppendLine("#nullable disable");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace UnaPartidaMas.Valkarn.Tasks.Bridge");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Generated extension methods for converting Unity Awaitable to ValkarnTask.");
            sb.AppendLine("    /// Direct 'await Awaitable' inside async ValkarnTask methods works without conversion.");
            sb.AppendLine("    /// Use .AsValkarnTask() when you need to pass an Awaitable to WhenAll/WhenAny or store it as ValkarnTask.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class AwaitableBridgeExtensions");
            sb.AppendLine("    {");

            if (info.HasAwaitable)
            {
                sb.AppendLine("        /// <summary>");
                sb.AppendLine("        /// Converts a Unity Awaitable to a ValkarnTask.");
                sb.AppendLine("        /// Uses ValkarnTask's pooled async runner — zero-alloc on warm pool.");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine("        public static async ValkarnTask AsValkarnTask(this Awaitable awaitable)");
                sb.AppendLine("        {");
                sb.AppendLine("            await awaitable;");
                sb.AppendLine("        }");
            }

            if (info.HasAwaitableT)
            {
                if (info.HasAwaitable) sb.AppendLine();
                sb.AppendLine("        /// <summary>");
                sb.AppendLine("        /// Converts a Unity Awaitable&lt;T&gt; to a ValkarnTask&lt;T&gt;.");
                sb.AppendLine("        /// Uses ValkarnTask's pooled async runner — zero-alloc on warm pool.");
                sb.AppendLine("        /// </summary>");
                sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine("        public static async ValkarnTask<T> AsValkarnTask<T>(this Awaitable<T> awaitable)");
                sb.AppendLine("        {");
                sb.AppendLine("            return await awaitable;");
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine("#endif");

            ctx.AddSource("ValkarnTask.AwaitableBridge.Generated.g.cs", sb.ToString());
        }

        // Equatable struct for incremental caching
        readonly struct AwaitableAvailability : System.IEquatable<AwaitableAvailability>
        {
            public readonly bool HasAwaitable;
            public readonly bool HasAwaitableT;

            public AwaitableAvailability(bool hasAwaitable, bool hasAwaitableT)
            {
                HasAwaitable = hasAwaitable;
                HasAwaitableT = hasAwaitableT;
            }

            public bool Equals(AwaitableAvailability other)
                => HasAwaitable == other.HasAwaitable && HasAwaitableT == other.HasAwaitableT;

            public override bool Equals(object obj)
                => obj is AwaitableAvailability other && Equals(other);

            public override int GetHashCode()
                => (HasAwaitable ? 1 : 0) | (HasAwaitableT ? 2 : 0);
        }
    }
}
