// Copyright (c) 2025 Una Partida Mas. All rights reserved.
// Licensed under the Valkarn Tasks License. See LICENSE.md in the repository root.

using System.Text;
using Microsoft.CodeAnalysis;

namespace UnaPartidaMas.Valkarn.Tasks.SourceGen.Generators
{
    [Generator(LanguageNames.CSharp)]
    public sealed class CombinatorGenerator : IIncrementalGenerator
    {
        // Arities 2 (WhenAll typed) and 2-3 (WhenAll void) and 2 (WhenAny void/typed) are hand-written.
        // This generator produces arities 3-8 for typed WhenAll, 4-8 for void WhenAll,
        // 3-8 for void WhenAny, and 3-8 for typed WhenAny.

        const int MinTypedWhenAllArity = 3;
        const int MinVoidWhenAllArity = 4;
        const int MinVoidWhenAnyArity = 3;
        const int MinTypedWhenAnyArity = 3;
        const int MaxArity = 8;

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Only generate combinators when ValkarnTask is defined in source (not just referenced).
            // This prevents CS0538 errors from injecting partial struct into assemblies
            // that only reference ValkarnTask via ProjectReference.
            var hasValkarnTaskDefined = context.CompilationProvider.Select(
                static (c, _) =>
                {
                    var valkarnType = c.GetTypeByMetadataName("UnaPartidaMas.Valkarn.Tasks.ValkarnTask");
                    return valkarnType != null
                        && SymbolEqualityComparer.Default.Equals(valkarnType.ContainingAssembly, c.Assembly);
                });

            context.RegisterSourceOutput(hasValkarnTaskDefined, static (ctx, defined) =>
            {
                if (!defined) return;
                ctx.AddSource("ValkarnTask.WhenAll.Generated.g.cs", GenerateWhenAllSource());
                ctx.AddSource("ValkarnTask.WhenAny.Generated.g.cs", GenerateWhenAnySource());
            });
        }

        // ════════════════════════════════════════════════════════════════
        //  WhenAll Generation
        // ════════════════════════════════════════════════════════════════

        static string GenerateWhenAllSource()
        {
            var sb = new StringBuilder(32768);
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable disable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine();
            sb.AppendLine("namespace UnaPartidaMas.Valkarn.Tasks");
            sb.AppendLine("{");

            // Public API methods on ValkarnTask
            sb.AppendLine("    public readonly partial struct ValkarnTask");
            sb.AppendLine("    {");
            for (int n = MinTypedWhenAllArity; n <= MaxArity; n++)
                EmitWhenAllTypedApiMethod(sb, n);
            for (int n = MinVoidWhenAllArity; n <= MaxArity; n++)
                EmitWhenAllVoidApiMethod(sb, n);
            sb.AppendLine("    }");
            sb.AppendLine();

            // Promise types
            for (int n = MinTypedWhenAllArity; n <= MaxArity; n++)
            {
                EmitWhenAllTypedPromise(sb, n);
                sb.AppendLine();
            }
            for (int n = MinVoidWhenAllArity; n <= MaxArity; n++)
            {
                EmitWhenAllVoidPromise(sb, n);
                sb.AppendLine();
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        static void EmitWhenAllTypedApiMethod(StringBuilder sb, int n)
        {
            var tParams = TypeParams(n);
            var rawTuple = RawTuple(n);

            sb.AppendLine();
            sb.AppendLine($"        /// <summary>Awaits all {n} tasks concurrently, returning a tuple of results.");
            sb.AppendLine($"        /// Throws if any task faults or is canceled (first exception wins).");
            sb.AppendLine($"        /// Zero-alloc when all sync-completed.</summary>");
            sb.Append($"        public static ValkarnTask<{rawTuple}> WhenAll<{tParams}>(");
            sb.Append(TaskParamsTyped(n));
            sb.AppendLine(")");
            sb.AppendLine("        {");

            // Fast path: all sources null
            sb.Append("            if (");
            for (int i = 1; i <= n; i++)
            {
                if (i > 1) sb.Append(" && ");
                sb.Append($"task{i}.source == null");
            }
            sb.AppendLine(")");
            sb.Append("                return new ValkarnTask<");
            sb.Append(rawTuple);
            sb.Append(">((");
            for (int i = 1; i <= n; i++)
            {
                if (i > 1) sb.Append(", ");
                sb.Append($"task{i}.result");
            }
            sb.AppendLine("));");
            sb.AppendLine();
            sb.AppendLine($"            return WhenAllPromise{n}<{tParams}>.Create({InArgs(n)});");
            sb.AppendLine("        }");
        }

        static void EmitWhenAllVoidApiMethod(StringBuilder sb, int n)
        {
            sb.AppendLine();
            sb.AppendLine($"        /// <summary>Awaits all {n} void tasks concurrently.");
            sb.AppendLine($"        /// Throws if any task faults or is canceled.</summary>");
            sb.Append($"        public static ValkarnTask WhenAll(");
            sb.Append(TaskParamsVoid(n));
            sb.AppendLine(")");
            sb.AppendLine("        {");

            // Fast path: all sources null
            sb.Append("            if (");
            for (int i = 1; i <= n; i++)
            {
                if (i > 1) sb.Append(" && ");
                sb.Append($"task{i}.source == null");
            }
            sb.AppendLine(")");
            sb.AppendLine("                return CompletedTask;");
            sb.AppendLine();
            sb.AppendLine($"            return WhenAllVoidPromise{n}.Create({InArgs(n)}).AsNonGeneric();");
            sb.AppendLine("        }");
        }

        static void EmitWhenAllTypedPromise(StringBuilder sb, int n)
        {
            var tParams = TypeParams(n);
            var rawTuple = RawTuple(n);
            var className = $"WhenAllPromise{n}<{tParams}>";
            var classNameRaw = $"WhenAllPromise{n}";

            sb.AppendLine($"    internal sealed class {classNameRaw}<{tParams}>");
            sb.AppendLine($"        : ValkarnTask.ISource<{rawTuple}>,");
            sb.AppendLine($"          IPoolNode<{className}>");
            sb.AppendLine("    {");

            // Pool
            sb.AppendLine($"        static ValkarnPool<{className}> s_pool;");
            sb.AppendLine($"        static ValkarnPool<{className}> Pool => ValkarnPool<{className}>.GetOrCreate(ref s_pool);");
            sb.AppendLine($"        {className} nextNode;");
            sb.AppendLine($"        public ref {className} NextNode => ref nextNode;");
            sb.AppendLine();

            // Fields — raw results, firstException/firstCancellation
            sb.AppendLine($"        ValkarnCompletionCore<{rawTuple}> core;");
            sb.AppendLine("        int returned;");
            for (int i = 1; i <= n; i++)
            {
                sb.AppendLine($"        ValkarnTask.ISource<T{i}> source{i};");
                sb.AppendLine($"        uint token{i};");
                sb.AppendLine($"        T{i} result{i};");
            }
            sb.AppendLine("        Exception firstException;");
            sb.AppendLine("        OperationCanceledException firstCancellation;");
            sb.AppendLine("        int remainingCount;");
            sb.AppendLine();

            // Static callbacks — try/catch with firstException pattern
            for (int i = 1; i <= n; i++)
            {
                sb.AppendLine($"        static readonly Action<object> s_callback{i} = static state =>");
                sb.AppendLine("        {");
                sb.AppendLine($"            var self = ({className})state;");
                sb.AppendLine($"            try {{ self.result{i} = self.source{i}.GetResult(self.token{i}); }}");
                sb.AppendLine($"            catch (OperationCanceledException oce) {{ Interlocked.CompareExchange(ref self.firstCancellation, oce, null); }}");
                sb.AppendLine("            catch (Exception ex) { if (Interlocked.CompareExchange(ref self.firstException, ex, null) != null) ValkarnTask.PublishUnobservedException(ex); }");
                sb.AppendLine($"            self.source{i} = null;");
                sb.AppendLine("            if (Interlocked.Decrement(ref self.remainingCount) == 0)");
                sb.AppendLine("                self.Complete();");
                sb.AppendLine("        };");
                sb.AppendLine();
            }

            // Private ctor
            sb.AppendLine($"        {classNameRaw}() {{ }}");
            sb.AppendLine();

            // Complete method
            sb.AppendLine("        void Complete()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (firstException != null)");
            sb.AppendLine("                core.TrySetException(firstException);");
            sb.AppendLine("            else if (firstCancellation != null)");
            sb.AppendLine("                core.TrySetCanceled(firstCancellation.CancellationToken);");
            sb.AppendLine("            else");
            sb.Append("                core.TrySetResult((");
            for (int j = 1; j <= n; j++)
            {
                if (j > 1) sb.Append(", ");
                sb.Append($"result{j}");
            }
            sb.AppendLine("));");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Create method
            sb.Append($"        internal static ValkarnTask<{rawTuple}> Create(");
            for (int i = 1; i <= n; i++)
            {
                if (i > 1) sb.Append(", ");
                sb.Append($"ValkarnTask<T{i}> task{i}");
            }
            sb.AppendLine(")");
            sb.AppendLine("        {");
            sb.AppendLine($"            var p = Pool.TryRent() ?? Pool.TrackNew(new {classNameRaw}<{tParams}>());");
            sb.AppendLine("            var outToken = p.core.Token;");
            sb.AppendLine("            p.returned = 0;");
            sb.AppendLine($"            p.remainingCount = {n + 1}; // {n} tasks + 1 guard");
            sb.AppendLine("            p.firstException = null;");
            sb.AppendLine("            p.firstCancellation = null;");
            sb.AppendLine();

            for (int i = 1; i <= n; i++)
            {
                sb.AppendLine($"            if (task{i}.source == null)");
                sb.AppendLine("            {");
                sb.AppendLine($"                p.result{i} = task{i}.result;");
                sb.AppendLine("                Interlocked.Decrement(ref p.remainingCount);");
                sb.AppendLine("            }");
                sb.AppendLine("            else");
                sb.AppendLine("            {");
                sb.AppendLine($"                p.source{i} = task{i}.source;");
                sb.AppendLine($"                p.token{i} = task{i}.token;");
                sb.AppendLine($"                task{i}.source.OnCompleted(s_callback{i}, p, task{i}.token);");
                sb.AppendLine("            }");
                sb.AppendLine();
            }

            // Release guard
            sb.AppendLine("            if (Interlocked.Decrement(ref p.remainingCount) == 0)");
            sb.AppendLine("                p.Complete();");
            sb.AppendLine();
            sb.AppendLine($"            return new ValkarnTask<{rawTuple}>(p, outToken);");
            sb.AppendLine("        }");
            sb.AppendLine();

            // ISource implementation
            sb.AppendLine("        ValkarnTask.Status ValkarnTask.ISource.GetStatus(uint token) => core.GetStatus(token);");
            sb.AppendLine("        ValkarnTask.Status ValkarnTask.ISource.UnsafeGetStatus() => core.UnsafeGetStatus();");
            sb.AppendLine();
            sb.AppendLine($"        {rawTuple} ValkarnTask.ISource<{rawTuple}>.GetResult(uint token)");
            sb.AppendLine("        {");
            sb.AppendLine("            try { return core.GetResult(token); }");
            sb.AppendLine("            finally { TryReturn(); }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        void ValkarnTask.ISource.GetResult(uint token)");
            sb.AppendLine("        {");
            sb.AppendLine("            try { core.GetResult(token); }");
            sb.AppendLine("            finally { TryReturn(); }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        void ValkarnTask.ISource.OnCompleted(Action<object> continuation, object state, uint token)");
            sb.AppendLine("            => core.OnCompleted(continuation, state, token);");
            sb.AppendLine();

            // TryReturn
            sb.AppendLine("        void TryReturn()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (Interlocked.Exchange(ref returned, 1) != 0) return;");
            for (int i = 1; i <= n; i++)
            {
                sb.AppendLine($"            source{i} = null;");
                sb.AppendLine($"            result{i} = default;");
            }
            sb.AppendLine("            firstException = null;");
            sb.AppendLine("            firstCancellation = null;");
            sb.AppendLine("            core.Reset();");
            sb.AppendLine("            Pool.TryReturn(this);");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
        }

        static void EmitWhenAllVoidPromise(StringBuilder sb, int n)
        {
            var className = $"WhenAllVoidPromise{n}";

            sb.AppendLine($"    internal sealed class {className}");
            sb.AppendLine($"        : ValkarnTask.ISource<AsyncUnit>,");
            sb.AppendLine($"          IPoolNode<{className}>");
            sb.AppendLine("    {");

            // Pool
            sb.AppendLine($"        static ValkarnPool<{className}> s_pool;");
            sb.AppendLine($"        static ValkarnPool<{className}> Pool => ValkarnPool<{className}>.GetOrCreate(ref s_pool);");
            sb.AppendLine($"        {className} nextNode;");
            sb.AppendLine($"        public ref {className} NextNode => ref nextNode;");
            sb.AppendLine();

            // Fields — firstException/firstCancellation pattern
            sb.AppendLine("        ValkarnCompletionCore<AsyncUnit> core;");
            sb.AppendLine("        int returned;");
            for (int i = 1; i <= n; i++)
            {
                sb.AppendLine($"        ValkarnTask.ISource source{i};");
                sb.AppendLine($"        uint token{i};");
            }
            sb.AppendLine("        Exception firstException;");
            sb.AppendLine("        OperationCanceledException firstCancellation;");
            sb.AppendLine("        int remainingCount;");
            sb.AppendLine();

            // Static callbacks
            for (int i = 1; i <= n; i++)
            {
                sb.AppendLine($"        static readonly Action<object> s_callback{i} = static state =>");
                sb.AppendLine("        {");
                sb.AppendLine($"            var self = ({className})state;");
                sb.AppendLine($"            try {{ self.source{i}.GetResult(self.token{i}); }}");
                sb.AppendLine("            catch (OperationCanceledException oce) { Interlocked.CompareExchange(ref self.firstCancellation, oce, null); }");
                sb.AppendLine("            catch (Exception ex) { if (Interlocked.CompareExchange(ref self.firstException, ex, null) != null) ValkarnTask.PublishUnobservedException(ex); }");
                sb.AppendLine($"            self.source{i} = null;");
                sb.AppendLine("            if (Interlocked.Decrement(ref self.remainingCount) == 0)");
                sb.AppendLine("                self.Complete();");
                sb.AppendLine("        };");
                sb.AppendLine();
            }

            // Private ctor
            sb.AppendLine($"        {className}() {{ }}");
            sb.AppendLine();

            // Complete method
            sb.AppendLine("        void Complete()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (firstException != null)");
            sb.AppendLine("                core.TrySetException(firstException);");
            sb.AppendLine("            else if (firstCancellation != null)");
            sb.AppendLine("                core.TrySetCanceled(firstCancellation.CancellationToken);");
            sb.AppendLine("            else");
            sb.AppendLine("                core.TrySetResult(AsyncUnit.Default);");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Create method
            sb.Append($"        internal static ValkarnTask<AsyncUnit> Create(");
            for (int i = 1; i <= n; i++)
            {
                if (i > 1) sb.Append(", ");
                sb.Append($"ValkarnTask task{i}");
            }
            sb.AppendLine(")");
            sb.AppendLine("        {");
            sb.AppendLine($"            var p = Pool.TryRent() ?? Pool.TrackNew(new {className}());");
            sb.AppendLine("            var outToken = p.core.Token;");
            sb.AppendLine("            p.returned = 0;");
            sb.AppendLine($"            p.remainingCount = {n + 1}; // {n} tasks + 1 guard");
            sb.AppendLine("            p.firstException = null;");
            sb.AppendLine("            p.firstCancellation = null;");
            sb.AppendLine();

            for (int i = 1; i <= n; i++)
            {
                sb.AppendLine($"            if (task{i}.source == null)");
                sb.AppendLine("            {");
                sb.AppendLine("                Interlocked.Decrement(ref p.remainingCount);");
                sb.AppendLine("            }");
                sb.AppendLine("            else");
                sb.AppendLine("            {");
                sb.AppendLine($"                p.source{i} = task{i}.source;");
                sb.AppendLine($"                p.token{i} = task{i}.token;");
                sb.AppendLine($"                task{i}.source.OnCompleted(s_callback{i}, p, task{i}.token);");
                sb.AppendLine("            }");
                sb.AppendLine();
            }

            sb.AppendLine("            if (Interlocked.Decrement(ref p.remainingCount) == 0)");
            sb.AppendLine("                p.Complete();");
            sb.AppendLine();
            sb.AppendLine($"            return new ValkarnTask<AsyncUnit>(p, outToken);");
            sb.AppendLine("        }");
            sb.AppendLine();

            // ISource
            sb.AppendLine("        ValkarnTask.Status ValkarnTask.ISource.GetStatus(uint token) => core.GetStatus(token);");
            sb.AppendLine("        ValkarnTask.Status ValkarnTask.ISource.UnsafeGetStatus() => core.UnsafeGetStatus();");
            sb.AppendLine();
            sb.AppendLine("        AsyncUnit ValkarnTask.ISource<AsyncUnit>.GetResult(uint token)");
            sb.AppendLine("        {");
            sb.AppendLine("            try { return core.GetResult(token); }");
            sb.AppendLine("            finally { TryReturn(); }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        void ValkarnTask.ISource.GetResult(uint token)");
            sb.AppendLine("        {");
            sb.AppendLine("            try { core.GetResult(token); }");
            sb.AppendLine("            finally { TryReturn(); }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        void ValkarnTask.ISource.OnCompleted(Action<object> continuation, object state, uint token)");
            sb.AppendLine("            => core.OnCompleted(continuation, state, token);");
            sb.AppendLine();

            // TryReturn
            sb.AppendLine("        void TryReturn()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (Interlocked.Exchange(ref returned, 1) != 0) return;");
            for (int i = 1; i <= n; i++)
                sb.AppendLine($"            source{i} = null;");
            sb.AppendLine("            firstException = null;");
            sb.AppendLine("            firstCancellation = null;");
            sb.AppendLine("            core.Reset();");
            sb.AppendLine("            Pool.TryReturn(this);");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
        }

        // ════════════════════════════════════════════════════════════════
        //  WhenAny Generation (void, arities 3-8)
        // ════════════════════════════════════════════════════════════════

        static string GenerateWhenAnySource()
        {
            var sb = new StringBuilder(32768);
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable disable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine();
            sb.AppendLine("namespace UnaPartidaMas.Valkarn.Tasks");
            sb.AppendLine("{");

            // Public API
            sb.AppendLine("    public readonly partial struct ValkarnTask");
            sb.AppendLine("    {");
            for (int n = MinVoidWhenAnyArity; n <= MaxArity; n++)
                EmitWhenAnyVoidApiMethod(sb, n);
            for (int n = MinTypedWhenAnyArity; n <= MaxArity; n++)
                EmitWhenAnyTypedApiMethod(sb, n);
            sb.AppendLine("    }");
            sb.AppendLine();

            // Promise types — void
            for (int n = MinVoidWhenAnyArity; n <= MaxArity; n++)
            {
                EmitWhenAnyVoidPromise(sb, n);
                sb.AppendLine();
            }

            // Promise types — typed
            for (int n = MinTypedWhenAnyArity; n <= MaxArity; n++)
            {
                EmitWhenAnyTypedPromise(sb, n);
                sb.AppendLine();
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        static void EmitWhenAnyVoidApiMethod(StringBuilder sb, int n)
        {
            sb.AppendLine();
            sb.AppendLine($"        /// <summary>Returns the 0-based index of the first completed void task out of {n}.</summary>");
            sb.Append($"        public static ValkarnTask<int> WhenAny(");
            sb.Append(TaskParamsVoid(n));
            sb.AppendLine(")");
            sb.AppendLine("        {");
            sb.AppendLine("            // Fast path: task1 sync-completed — zero alloc");
            sb.AppendLine("            if (task1.source == null)");
            sb.AppendLine("                return new ValkarnTask<int>(0);");
            sb.AppendLine($"            return WhenAnyVoidPromise{n}.Create({InArgs(n)});");
            sb.AppendLine("        }");
        }

        static void EmitWhenAnyVoidPromise(StringBuilder sb, int n)
        {
            var className = $"WhenAnyVoidPromise{n}";

            sb.AppendLine($"    internal sealed class {className}");
            sb.AppendLine($"        : ValkarnTask.ISource<int>,");
            sb.AppendLine($"          IPoolNode<{className}>");
            sb.AppendLine("    {");

            // Pool
            sb.AppendLine($"        static ValkarnPool<{className}> s_pool;");
            sb.AppendLine($"        static ValkarnPool<{className}> Pool => ValkarnPool<{className}>.GetOrCreate(ref s_pool);");
            sb.AppendLine($"        {className} nextNode;");
            sb.AppendLine($"        public ref {className} NextNode => ref nextNode;");
            sb.AppendLine();

            // Fields
            sb.AppendLine("        ValkarnCompletionCore<int> core;");
            sb.AppendLine("        int returned;");
            for (int i = 1; i <= n; i++)
            {
                sb.AppendLine($"        ValkarnTask.ISource source{i};");
                sb.AppendLine($"        uint token{i};");
            }
            sb.AppendLine("        int winnerIndex;");
            sb.AppendLine("        int returnGuard;");
            sb.AppendLine();

            // Static callbacks — with returnGuard decrement and loser cancellation comment
            for (int i = 1; i <= n; i++)
            {
                sb.AppendLine($"        static readonly Action<object> s_callback{i} = static state =>");
                sb.AppendLine("        {");
                sb.AppendLine($"            var self = ({className})state;");
                sb.AppendLine($"            bool isWinner = Interlocked.CompareExchange(ref self.winnerIndex, {i - 1}, -1) == -1;");
                sb.AppendLine("            try");
                sb.AppendLine("            {");
                sb.AppendLine($"                self.source{i}.GetResult(self.token{i});");
                sb.AppendLine($"                if (isWinner) self.core.TrySetResult({i - 1});");
                sb.AppendLine("            }");
                sb.AppendLine("            catch (OperationCanceledException oce)");
                sb.AppendLine("            {");
                sb.AppendLine("                if (isWinner) self.core.TrySetCanceled(oce.CancellationToken);");
                sb.AppendLine("                // Loser cancellation intentionally not reported");
                sb.AppendLine("            }");
                sb.AppendLine("            catch (Exception ex)");
                sb.AppendLine("            {");
                sb.AppendLine("                if (isWinner) self.core.TrySetException(ex);");
                sb.AppendLine("                else ValkarnTask.PublishUnobservedException(ex);");
                sb.AppendLine("            }");
                sb.AppendLine($"            self.source{i} = null;");
                sb.AppendLine("            if (Interlocked.Decrement(ref self.returnGuard) == 0)");
                sb.AppendLine("                self.TryReturn();");
                sb.AppendLine("        };");
                sb.AppendLine();
            }

            // Private ctor
            sb.AppendLine($"        {className}() {{ }}");
            sb.AppendLine();

            // Create — with pool rent and returnGuard
            sb.Append($"        internal static ValkarnTask<int> Create(");
            for (int i = 1; i <= n; i++)
            {
                if (i > 1) sb.Append(", ");
                sb.Append($"ValkarnTask task{i}");
            }
            sb.AppendLine(")");
            sb.AppendLine("        {");
            sb.AppendLine($"            var p = Pool.TryRent() ?? Pool.TrackNew(new {className}());");
            sb.AppendLine("            var outToken = p.core.Token;");
            sb.AppendLine("            p.returned = 0;");
            sb.AppendLine("            p.winnerIndex = -1;");
            sb.AppendLine($"            p.returnGuard = {n + 1}; // {n} potential callbacks + 1 GetResult");
            sb.AppendLine();

            for (int i = 1; i <= n; i++)
            {
                sb.AppendLine($"            if (task{i}.source == null)");
                sb.AppendLine("            {");
                sb.AppendLine($"                if (Interlocked.CompareExchange(ref p.winnerIndex, {i - 1}, -1) == -1)");
                sb.AppendLine($"                    p.core.TrySetResult({i - 1});");
                sb.AppendLine("                Interlocked.Decrement(ref p.returnGuard);");
                sb.AppendLine("            }");
                sb.AppendLine($"            else if (task{i}.source is NeverSource)");
                sb.AppendLine("            {");
                sb.AppendLine("                // NeverSource.OnCompleted is a no-op; pre-decrement to avoid permanent pool leak");
                sb.AppendLine("                Interlocked.Decrement(ref p.returnGuard);");
                sb.AppendLine("            }");
                sb.AppendLine("            else");
                sb.AppendLine("            {");
                sb.AppendLine($"                p.source{i} = task{i}.source;");
                sb.AppendLine($"                p.token{i} = task{i}.token;");
                sb.AppendLine($"                task{i}.source.OnCompleted(s_callback{i}, p, task{i}.token);");
                sb.AppendLine("            }");
                sb.AppendLine();
            }

            sb.AppendLine("            return new ValkarnTask<int>(p, outToken);");
            sb.AppendLine("        }");
            sb.AppendLine();

            // ISource — GetResult with returnGuard
            sb.AppendLine("        ValkarnTask.Status ValkarnTask.ISource.GetStatus(uint token) => core.GetStatus(token);");
            sb.AppendLine("        ValkarnTask.Status ValkarnTask.ISource.UnsafeGetStatus() => core.UnsafeGetStatus();");
            sb.AppendLine();
            sb.AppendLine("        int ValkarnTask.ISource<int>.GetResult(uint token)");
            sb.AppendLine("        {");
            sb.AppendLine("            try { return core.GetResult(token); }");
            sb.AppendLine("            finally");
            sb.AppendLine("            {");
            sb.AppendLine("                if (Interlocked.Decrement(ref returnGuard) == 0)");
            sb.AppendLine("                    TryReturn();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        void ValkarnTask.ISource.GetResult(uint token)");
            sb.AppendLine("        {");
            sb.AppendLine("            try { core.GetResult(token); }");
            sb.AppendLine("            finally");
            sb.AppendLine("            {");
            sb.AppendLine("                if (Interlocked.Decrement(ref returnGuard) == 0)");
            sb.AppendLine("                    TryReturn();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        void ValkarnTask.ISource.OnCompleted(Action<object> continuation, object state, uint token)");
            sb.AppendLine("            => core.OnCompleted(continuation, state, token);");
            sb.AppendLine();

            // TryReturn
            sb.AppendLine("        void TryReturn()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (Interlocked.Exchange(ref returned, 1) != 0) return;");
            for (int i = 1; i <= n; i++)
                sb.AppendLine($"            source{i} = null;");
            sb.AppendLine("            winnerIndex = 0;");
            sb.AppendLine("            core.Reset();");
            sb.AppendLine("            Pool.TryReturn(this);");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
        }

        // ════════════════════════════════════════════════════════════════
        //  WhenAny Generation (typed, arities 3-8)
        // ════════════════════════════════════════════════════════════════

        static void EmitWhenAnyTypedApiMethod(StringBuilder sb, int n)
        {
            sb.AppendLine();
            sb.AppendLine($"        /// <summary>Returns the first completed typed result out of {n} homogeneous tasks (0-based index).</summary>");
            sb.Append($"        public static ValkarnTask<(int, T)> WhenAny<T>(");
            sb.Append(TaskParamsHomogeneous(n));
            sb.AppendLine(")");
            sb.AppendLine("        {");
            sb.AppendLine("            // Fast path: task1 sync-completed — zero alloc");
            sb.AppendLine("            if (task1.source == null)");
            sb.AppendLine("                return new ValkarnTask<(int, T)>((0, task1.result));");
            sb.AppendLine($"            return WhenAnyTypedPromise{n}<T>.Create({InArgs(n)});");
            sb.AppendLine("        }");
        }

        static void EmitWhenAnyTypedPromise(StringBuilder sb, int n)
        {
            var className = $"WhenAnyTypedPromise{n}<T>";
            var classNameRaw = $"WhenAnyTypedPromise{n}";

            sb.AppendLine($"    internal sealed class {classNameRaw}<T>");
            sb.AppendLine($"        : ValkarnTask.ISource<(int, T)>,");
            sb.AppendLine($"          IPoolNode<{className}>");
            sb.AppendLine("    {");

            // Pool
            sb.AppendLine($"        static ValkarnPool<{className}> s_pool;");
            sb.AppendLine($"        static ValkarnPool<{className}> Pool => ValkarnPool<{className}>.GetOrCreate(ref s_pool);");
            sb.AppendLine($"        {className} nextNode;");
            sb.AppendLine($"        public ref {className} NextNode => ref nextNode;");
            sb.AppendLine();

            // Fields
            sb.AppendLine("        ValkarnCompletionCore<(int, T)> core;");
            sb.AppendLine("        int returned;");
            for (int i = 1; i <= n; i++)
            {
                sb.AppendLine($"        ValkarnTask.ISource<T> source{i};");
                sb.AppendLine($"        uint token{i};");
            }
            sb.AppendLine("        int winnerIndex;");
            sb.AppendLine("        int returnGuard;");
            sb.AppendLine();

            // Static callbacks — with returnGuard and loser cancellation comment
            for (int i = 1; i <= n; i++)
            {
                sb.AppendLine($"        static readonly Action<object> s_callback{i} = static state =>");
                sb.AppendLine("        {");
                sb.AppendLine($"            var self = ({className})state;");
                sb.AppendLine($"            bool isWinner = Interlocked.CompareExchange(ref self.winnerIndex, {i - 1}, -1) == -1;");
                sb.AppendLine("            try");
                sb.AppendLine("            {");
                sb.AppendLine($"                var value = self.source{i}.GetResult(self.token{i});");
                sb.AppendLine($"                if (isWinner) self.core.TrySetResult(({i - 1}, value));");
                sb.AppendLine("            }");
                sb.AppendLine("            catch (OperationCanceledException oce)");
                sb.AppendLine("            {");
                sb.AppendLine("                if (isWinner) self.core.TrySetCanceled(oce.CancellationToken);");
                sb.AppendLine("                // Loser cancellation intentionally not reported");
                sb.AppendLine("            }");
                sb.AppendLine("            catch (Exception ex)");
                sb.AppendLine("            {");
                sb.AppendLine("                if (isWinner) self.core.TrySetException(ex);");
                sb.AppendLine("                else ValkarnTask.PublishUnobservedException(ex);");
                sb.AppendLine("            }");
                sb.AppendLine($"            self.source{i} = null;");
                sb.AppendLine("            if (Interlocked.Decrement(ref self.returnGuard) == 0)");
                sb.AppendLine("                self.TryReturn();");
                sb.AppendLine("        };");
                sb.AppendLine();
            }

            // Private ctor
            sb.AppendLine($"        {classNameRaw}() {{ }}");
            sb.AppendLine();

            // Create — with pool rent and returnGuard
            sb.Append($"        internal static ValkarnTask<(int, T)> Create(");
            for (int i = 1; i <= n; i++)
            {
                if (i > 1) sb.Append(", ");
                sb.Append($"ValkarnTask<T> task{i}");
            }
            sb.AppendLine(")");
            sb.AppendLine("        {");
            sb.AppendLine($"            var p = Pool.TryRent() ?? Pool.TrackNew(new {classNameRaw}<T>());");
            sb.AppendLine("            var outToken = p.core.Token;");
            sb.AppendLine("            p.returned = 0;");
            sb.AppendLine("            p.winnerIndex = -1;");
            sb.AppendLine($"            p.returnGuard = {n + 1}; // {n} potential callbacks + 1 GetResult");
            sb.AppendLine();

            for (int i = 1; i <= n; i++)
            {
                sb.AppendLine($"            if (task{i}.source == null)");
                sb.AppendLine("            {");
                sb.AppendLine($"                if (Interlocked.CompareExchange(ref p.winnerIndex, {i - 1}, -1) == -1)");
                sb.AppendLine($"                    p.core.TrySetResult(({i - 1}, task{i}.result));");
                sb.AppendLine("                Interlocked.Decrement(ref p.returnGuard);");
                sb.AppendLine("            }");
                // NeverSource only implements ISource (non-generic), not ISource<T>,
                // so a typed ValkarnTask<T> can never carry a NeverSource. No check needed.
                sb.AppendLine("            else");
                sb.AppendLine("            {");
                sb.AppendLine($"                p.source{i} = task{i}.source;");
                sb.AppendLine($"                p.token{i} = task{i}.token;");
                sb.AppendLine($"                task{i}.source.OnCompleted(s_callback{i}, p, task{i}.token);");
                sb.AppendLine("            }");
                sb.AppendLine();
            }

            sb.AppendLine("            return new ValkarnTask<(int, T)>(p, outToken);");
            sb.AppendLine("        }");
            sb.AppendLine();

            // ISource — GetResult with returnGuard
            sb.AppendLine("        ValkarnTask.Status ValkarnTask.ISource.GetStatus(uint token) => core.GetStatus(token);");
            sb.AppendLine("        ValkarnTask.Status ValkarnTask.ISource.UnsafeGetStatus() => core.UnsafeGetStatus();");
            sb.AppendLine();
            sb.AppendLine("        (int, T) ValkarnTask.ISource<(int, T)>.GetResult(uint token)");
            sb.AppendLine("        {");
            sb.AppendLine("            try { return core.GetResult(token); }");
            sb.AppendLine("            finally");
            sb.AppendLine("            {");
            sb.AppendLine("                if (Interlocked.Decrement(ref returnGuard) == 0)");
            sb.AppendLine("                    TryReturn();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        void ValkarnTask.ISource.GetResult(uint token)");
            sb.AppendLine("        {");
            sb.AppendLine("            try { core.GetResult(token); }");
            sb.AppendLine("            finally");
            sb.AppendLine("            {");
            sb.AppendLine("                if (Interlocked.Decrement(ref returnGuard) == 0)");
            sb.AppendLine("                    TryReturn();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        void ValkarnTask.ISource.OnCompleted(Action<object> continuation, object state, uint token)");
            sb.AppendLine("            => core.OnCompleted(continuation, state, token);");
            sb.AppendLine();

            // TryReturn
            sb.AppendLine("        void TryReturn()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (Interlocked.Exchange(ref returned, 1) != 0) return;");
            for (int i = 1; i <= n; i++)
                sb.AppendLine($"            source{i} = null;");
            sb.AppendLine("            winnerIndex = 0;");
            sb.AppendLine("            core.Reset();");
            sb.AppendLine("            Pool.TryReturn(this);");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
        }

        // ════════════════════════════════════════════════════════════════
        //  Helpers
        // ════════════════════════════════════════════════════════════════

        static string TypeParams(int n)
        {
            var sb = new StringBuilder();
            for (int i = 1; i <= n; i++)
            {
                if (i > 1) sb.Append(", ");
                sb.Append($"T{i}");
            }
            return sb.ToString();
        }

        static string RawTuple(int n)
        {
            var sb = new StringBuilder("(");
            for (int i = 1; i <= n; i++)
            {
                if (i > 1) sb.Append(", ");
                sb.Append($"T{i}");
            }
            sb.Append(")");
            return sb.ToString();
        }

        static string TaskParamsTyped(int n)
        {
            var sb = new StringBuilder();
            for (int i = 1; i <= n; i++)
            {
                if (i > 1) sb.Append(", ");
                sb.Append($"ValkarnTask<T{i}> task{i}");
            }
            return sb.ToString();
        }

        static string TaskParamsHomogeneous(int n)
        {
            var sb = new StringBuilder();
            for (int i = 1; i <= n; i++)
            {
                if (i > 1) sb.Append(", ");
                sb.Append($"ValkarnTask<T> task{i}");
            }
            return sb.ToString();
        }

        static string TaskParamsVoid(int n)
        {
            var sb = new StringBuilder();
            for (int i = 1; i <= n; i++)
            {
                if (i > 1) sb.Append(", ");
                sb.Append($"ValkarnTask task{i}");
            }
            return sb.ToString();
        }

        static string InArgs(int n)
        {
            var sb = new StringBuilder();
            for (int i = 1; i <= n; i++)
            {
                if (i > 1) sb.Append(", ");
                sb.Append($"task{i}");
            }
            return sb.ToString();
        }
    }
}
