// Copyright (c) 2025 Una Partida Mas. All rights reserved.
// Licensed under the Valkarn Tasks License. See LICENSE.md in the repository root.

using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace UnaPartidaMas.Valkarn.Tasks.SourceGen.Generators
{
    /// <summary>
    /// Detects structs implementing IJob, IJobParallelFor, or IJobFor and generates
    /// ScheduleAsync extension methods that wrap the job in a JobPromise for ValkarnTask.
    ///
    /// Design: architecture.md §3.4 and §11.2
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class JobBridgeGenerator : IIncrementalGenerator
    {
        // Job interfaces we look for
        static readonly string[] JobInterfaces = new[]
        {
            "Unity.Jobs.IJob",
            "Unity.Jobs.IJobParallelFor",
            "Unity.Jobs.IJobFor"
        };

        const string ValkarnTaskFullName = "UnaPartidaMas.Valkarn.Tasks.ValkarnTask";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Find all struct declarations that implement job interfaces
            var jobStructs = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is StructDeclarationSyntax sds
                    && sds.BaseList != null
                    && sds.BaseList.Types.Count > 0,
                transform: static (ctx, ct) =>
                {
                    var structDecl = (StructDeclarationSyntax)ctx.Node;
                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(structDecl, ct) as INamedTypeSymbol;
                    if (symbol == null) return default;

                    // Skip non-public types (including private nested structs)
                    if (symbol.DeclaredAccessibility != Accessibility.Public)
                        return default;
                    // Also check all containing types are public
                    var outer = symbol.ContainingType;
                    while (outer != null)
                    {
                        if (outer.DeclaredAccessibility != Accessibility.Public)
                            return default;
                        outer = outer.ContainingType;
                    }

                    string jobInterface = null;
                    foreach (var iface in symbol.AllInterfaces)
                    {
                        var fullName = iface.ToDisplayString();
                        if (fullName == "Unity.Jobs.IJob")
                        {
                            jobInterface = "IJob";
                            break;
                        }
                        if (fullName == "Unity.Jobs.IJobParallelFor")
                        {
                            jobInterface = "IJobParallelFor";
                            break;
                        }
                        if (fullName == "Unity.Jobs.IJobFor")
                        {
                            jobInterface = "IJobFor";
                            break;
                        }
                    }

                    if (jobInterface == null) return default;

                    // Build the full type name including containing types for nested structs.
                    // e.g. "OuterClass.InnerJob" instead of just "InnerJob".
                    var typeName = BuildNestedTypeName(symbol);

                    return new JobInfo(
                        typeName,
                        symbol.ContainingNamespace?.ToDisplayString(),
                        jobInterface
                    );
                })
                .Where(static info => info.TypeName != null);

            // Combine with ValkarnTask availability check to avoid generating code
            // in assemblies that don't reference Valkarn.Tasks.
            var hasValkarnTask = context.CompilationProvider.Select(static (c, _) =>
                c.GetTypeByMetadataName(ValkarnTaskFullName) != null);

            context.RegisterSourceOutput(
                jobStructs.Collect().Combine(hasValkarnTask),
                static (ctx, pair) => GenerateExtensions(ctx, pair.Left, pair.Right));
        }

        static void GenerateExtensions(SourceProductionContext ctx, ImmutableArray<JobInfo> jobs, bool hasValkarnTask)
        {
            if (!hasValkarnTask || jobs.IsDefaultOrEmpty) return;

            var sb = new StringBuilder(4096);
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#if UNITY_2019_3_OR_NEWER");
            sb.AppendLine("#nullable disable");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using Unity.Jobs;");
            sb.AppendLine("using UnaPartidaMas.Valkarn.Tasks;");
            sb.AppendLine("using UnaPartidaMas.Valkarn.Tasks.Bridge;");
            sb.AppendLine();

            foreach (var job in jobs.Distinct())
            {
                var ns = job.FullNamespace;
                var hasNamespace = !string.IsNullOrEmpty(ns) && ns != "<global namespace>";

                if (hasNamespace)
                {
                    sb.AppendLine($"namespace {ns}");
                    sb.AppendLine("{");
                }

                var indent = hasNamespace ? "    " : "";

                // Sanitize class name: "Outer.Inner" → "Outer_Inner" for the extension class identifier
                var safeClassName = job.TypeName.Replace(".", "_");
                sb.AppendLine($"{indent}/// <summary>Generated async wrapper for {job.TypeName} ({job.JobInterface}).</summary>");
                sb.AppendLine($"{indent}public static class __{safeClassName}_AsyncExt");
                sb.AppendLine($"{indent}{{");

                switch (job.JobInterface)
                {
                    case "IJob":
                        sb.AppendLine($"{indent}    public static ValkarnTask ScheduleAsync(this ref {job.TypeName} job, CancellationToken ct = default)");
                        sb.AppendLine($"{indent}    {{");
                        sb.AppendLine($"{indent}        var handle = job.Schedule();");
                        sb.AppendLine($"{indent}        var promise = JobPromise<{job.TypeName}>.Create(handle, ct, out var token);");
                        sb.AppendLine($"{indent}        return new ValkarnTask(promise, token);");
                        sb.AppendLine($"{indent}    }}");
                        break;

                    case "IJobParallelFor":
                        sb.AppendLine($"{indent}    public static ValkarnTask ScheduleAsync(this ref {job.TypeName} job, int arrayLength, int innerLoopBatchCount, CancellationToken ct = default)");
                        sb.AppendLine($"{indent}    {{");
                        sb.AppendLine($"{indent}        var handle = job.Schedule(arrayLength, innerLoopBatchCount);");
                        sb.AppendLine($"{indent}        var promise = JobPromise<{job.TypeName}>.Create(handle, ct, out var token);");
                        sb.AppendLine($"{indent}        return new ValkarnTask(promise, token);");
                        sb.AppendLine($"{indent}    }}");
                        break;

                    case "IJobFor":
                        sb.AppendLine($"{indent}    public static ValkarnTask ScheduleAsync(this ref {job.TypeName} job, int arrayLength, CancellationToken ct = default)");
                        sb.AppendLine($"{indent}    {{");
                        sb.AppendLine($"{indent}        var handle = job.Schedule(arrayLength, default);");
                        sb.AppendLine($"{indent}        var promise = JobPromise<{job.TypeName}>.Create(handle, ct, out var token);");
                        sb.AppendLine($"{indent}        return new ValkarnTask(promise, token);");
                        sb.AppendLine($"{indent}    }}");
                        sb.AppendLine();
                        sb.AppendLine($"{indent}    public static ValkarnTask ScheduleParallelAsync(this ref {job.TypeName} job, int arrayLength, int innerLoopBatchCount, CancellationToken ct = default)");
                        sb.AppendLine($"{indent}    {{");
                        sb.AppendLine($"{indent}        var handle = job.ScheduleParallel(arrayLength, innerLoopBatchCount, default);");
                        sb.AppendLine($"{indent}        var promise = JobPromise<{job.TypeName}>.Create(handle, ct, out var token);");
                        sb.AppendLine($"{indent}        return new ValkarnTask(promise, token);");
                        sb.AppendLine($"{indent}    }}");
                        break;
                }

                sb.AppendLine($"{indent}}}");

                if (hasNamespace)
                    sb.AppendLine("}");

                sb.AppendLine();
            }

            sb.AppendLine("#endif");

            ctx.AddSource("ValkarnTask.JobBridge.Generated.g.cs", sb.ToString());
        }

        /// <summary>
        /// Builds "Outer.Inner.JobStruct" for nested types, or just "JobStruct" for top-level.
        /// </summary>
        static string BuildNestedTypeName(INamedTypeSymbol symbol)
        {
            if (symbol.ContainingType == null)
                return symbol.Name;

            // Walk up the containing type chain
            var parts = new System.Collections.Generic.List<string>();
            var current = symbol;
            while (current != null)
            {
                parts.Add(current.Name);
                current = current.ContainingType;
            }
            parts.Reverse();
            return string.Join(".", parts);
        }

        // Equatable struct for incremental caching
        readonly struct JobInfo : IEquatable<JobInfo>
        {
            public readonly string TypeName;
            public readonly string FullNamespace;
            public readonly string JobInterface;

            public JobInfo(string typeName, string fullNamespace, string jobInterface)
            {
                TypeName = typeName;
                FullNamespace = fullNamespace;
                JobInterface = jobInterface;
            }

            public bool Equals(JobInfo other)
                => TypeName == other.TypeName
                && FullNamespace == other.FullNamespace
                && JobInterface == other.JobInterface;

            public override bool Equals(object obj)
                => obj is JobInfo other && Equals(other);

            public override int GetHashCode()
            {
                unchecked
                {
                    int hash = 17;
                    hash = hash * 31 + (TypeName?.GetHashCode() ?? 0);
                    hash = hash * 31 + (FullNamespace?.GetHashCode() ?? 0);
                    hash = hash * 31 + (JobInterface?.GetHashCode() ?? 0);
                    return hash;
                }
            }

            public static bool operator ==(JobInfo left, JobInfo right) => left.Equals(right);
            public static bool operator !=(JobInfo left, JobInfo right) => !left.Equals(right);
        }
    }
}
