// Copyright (c) 2025 Una Partida Mas. All rights reserved.
// Licensed under the Valkarn Tasks License. See LICENSE.md in the repository root.

using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace UnaPartidaMas.Valkarn.Tasks.SourceGen.Generators
{
    /// <summary>
    /// Generates lifecycle auto-cancel bindings for MonoBehaviour-derived classes.
    /// For each partial MonoBehaviour that contains async ValkarnTask methods,
    /// emits a CancellationTokenSource linked to Unity's destroyCancellationToken.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class LifecycleBindingGenerator : IIncrementalGenerator
    {
        const string MonoBehaviourFull = "UnityEngine.MonoBehaviour";
        const string ValkarnTaskFull = "UnaPartidaMas.Valkarn.Tasks.ValkarnTask";
        const string NoAutoCancelFull = "UnaPartidaMas.Valkarn.Tasks.NoAutoCancelAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var candidates = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => IsCandidate(node),
                transform: static (ctx, ct) => Transform(ctx, ct))
                .Where(static x => x != null);

            context.RegisterSourceOutput(candidates, static (ctx, info) => Emit(ctx, info));
        }

        // Quick syntax filter: partial class with a base list
        static bool IsCandidate(SyntaxNode node)
        {
            if (node is not ClassDeclarationSyntax classDecl) return false;
            if (classDecl.BaseList == null) return false;
            return classDecl.Modifiers.Any(SyntaxKind.PartialKeyword);
        }

        static LifecycleInfo Transform(GeneratorSyntaxContext ctx, System.Threading.CancellationToken ct)
        {
            var classDecl = (ClassDeclarationSyntax)ctx.Node;
            var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl, ct);
            if (symbol == null) return null;

            // Only emit for the first partial declaration to avoid duplicates
            var firstDecl = symbol.DeclaringSyntaxReferences[0].GetSyntax(ct);
            if (!ReferenceEquals(classDecl, firstDecl)) return null;

            // Check if derives from MonoBehaviour
            if (!DerivesFrom(symbol, MonoBehaviourFull)) return null;

            // Collect async ValkarnTask methods without [NoAutoCancel]
            var methods = ImmutableArray.CreateBuilder<string>();
            foreach (var member in symbol.GetMembers())
            {
                if (member is not IMethodSymbol method) continue;
                if (!method.IsAsync) continue;
                if (!IsValkarnTaskReturn(method.ReturnType)) continue;
                if (HasAttribute(method, NoAutoCancelFull)) continue;
                methods.Add(method.Name);
            }

            if (methods.Count == 0) return null;

            return new LifecycleInfo(
                symbol.ContainingNamespace?.IsGlobalNamespace == true ? null : symbol.ContainingNamespace?.ToDisplayString(),
                symbol.Name,
                methods.ToImmutable());
        }

        static void Emit(SourceProductionContext ctx, LifecycleInfo info)
        {
            var sb = new StringBuilder(512);
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable disable");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine();

            if (info.Namespace != null)
            {
                sb.AppendLine($"namespace {info.Namespace}");
                sb.AppendLine("{");
            }

            var indent = info.Namespace != null ? "    " : "";

            sb.AppendLine($"{indent}partial class {info.ClassName}");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]");
            sb.AppendLine($"{indent}    CancellationTokenSource __valkarnTaskLifetimeCts;");
            sb.AppendLine();
            sb.AppendLine($"{indent}    /// <summary>");
            sb.AppendLine($"{indent}    /// Cancellation token that is triggered when this MonoBehaviour is destroyed.");
            sb.AppendLine($"{indent}    /// Auto-generated by ValkarnTask source generator.");
            sb.AppendLine($"{indent}    /// </summary>");
            sb.AppendLine($"{indent}    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]");
            sb.AppendLine($"{indent}    protected CancellationToken __ValkarnTaskLifetimeToken");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        get");
            sb.AppendLine($"{indent}        {{");
            sb.AppendLine($"{indent}            if (__valkarnTaskLifetimeCts == null)");
            sb.AppendLine($"{indent}                __valkarnTaskLifetimeCts = CancellationTokenSource.CreateLinkedTokenSource(destroyCancellationToken);");
            sb.AppendLine($"{indent}            return __valkarnTaskLifetimeCts.Token;");
            sb.AppendLine($"{indent}        }}");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");

            if (info.Namespace != null)
                sb.AppendLine("}");

            var hintPrefix = info.Namespace != null
                ? $"{info.Namespace}.{info.ClassName}"
                : info.ClassName;
            ctx.AddSource($"{hintPrefix}.LifecycleBinding.g.cs", sb.ToString());

            // Report TT010 informational diagnostic for each auto-cancelled method
            // (We don't have locations here since we're in source output, so skip per-method diagnostics)
        }

        static bool DerivesFrom(INamedTypeSymbol symbol, string baseTypeFull)
        {
            var current = symbol.BaseType;
            while (current != null)
            {
                if (current.ToDisplayString() == baseTypeFull)
                    return true;
                current = current.BaseType;
            }
            return false;
        }

        static bool IsValkarnTaskReturn(ITypeSymbol type)
        {
            if (type == null) return false;
            if (type.Name != "ValkarnTask") return false;
            return type.ContainingNamespace?.ToDisplayString() == "UnaPartidaMas.Valkarn.Tasks";
        }

        static bool HasAttribute(IMethodSymbol method, string attributeFull)
        {
            foreach (var attr in method.GetAttributes())
            {
                if (attr.AttributeClass?.ToDisplayString() == attributeFull)
                    return true;
            }
            return false;
        }

        // Equatable record struct for caching (required by incremental generator)
        sealed class LifecycleInfo : System.IEquatable<LifecycleInfo>
        {
            public readonly string Namespace;
            public readonly string ClassName;
            public readonly ImmutableArray<string> MethodNames;

            public LifecycleInfo(string ns, string className, ImmutableArray<string> methodNames)
            {
                Namespace = ns;
                ClassName = className;
                MethodNames = methodNames;
            }

            public bool Equals(LifecycleInfo other)
            {
                if (other is null) return false;
                if (Namespace != other.Namespace) return false;
                if (ClassName != other.ClassName) return false;
                if (MethodNames.Length != other.MethodNames.Length) return false;
                for (int i = 0; i < MethodNames.Length; i++)
                    if (MethodNames[i] != other.MethodNames[i]) return false;
                return true;
            }

            public override bool Equals(object obj) => obj is LifecycleInfo info && Equals(info);

            public override int GetHashCode()
            {
                unchecked
                {
                    int hash = 17;
                    hash = hash * 31 + (Namespace?.GetHashCode() ?? 0);
                    hash = hash * 31 + (ClassName?.GetHashCode() ?? 0);
                    foreach (var m in MethodNames)
                        hash = hash * 31 + m.GetHashCode();
                    return hash;
                }
            }
        }
    }
}
